---
openapi: 3.0.0
info:
  title: G-Mall API
  version: 1.0.0
servers:
  - url: https://api.g-mall.com/v1
paths:
  /checkout:
    post:
      summary: Checkout the items in the cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                  description: The unique identifier for the customer
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The unique identifier for the product
                      quantity:
                        type: integer
                        description: The quantity of the product
                      price:
                        type: number
                        description: The price of the product
              required:
                - customer_id
                - products
      responses:
        "200":
          description: Checkout successful
        "400":
          description: Invalid request
  /cart:
    get:
      summary: Retrieve the items in the cart
      parameters:
        - in: path
          name: customer_id
          description: The unique identifier for the customer
          schema:
            type: integer
      responses:
        "200":
          description: The items in the cart
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The unique identifier for the product
                    quantity:
                      type: integer
                      description: The quantity of the product
                    price:
                      type: number
                      description: The price of the product
        "404":
          description: Cart not found
    post:
      summary: Add an item to the cart
      parameters:
        - in: path
          name: customer_id
          description: The unique identifier for the customer
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                  description: The unique identifier for the product
                quantity:
                  type: integer
                  description: The quantity of the product
                price:
                  type: number
                  description: The price of the product
              required:
                - product_id
                - quantity
                - price
      responses:
        "201":
          description: Item added to cart
        "400":
          description: Invalid request
  /payment:
    post:
      summary: Process payment for an order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: integer
                  description: The unique identifier for the order
                payment_method:
                  type: string
                  description: The method of payment
                payment_details:
                  type: object
                  properties:
                    card_number:
                      type: string
                      description: The credit card number (if paying by credit card)
                    expiry_date:
                      type: string
                      format: mm/yy (if paying by credit card)
                    account_number:
                      type: string
                      description: The bank account number (if paying by bank transfer)
                    routing_number:
                      type: string
                      description: The bank routing number (if paying by bank transfer)
              required:
                - order_id
                - payment_method
                - payment_details
      responses:
        "200":
          description: Payment successful
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "404":
          description: Order not found
